# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Preprocessing.py
# Created on: 2024-02-02 19:59:13.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
Projected_Raster = "C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\Projected Raster"
ClipRaster = "C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\ClipRaster"
ResampleRaster = "C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\ResampleRaster"
normalization = "C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\normalization"
Mean = "C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\Mean"
Max = "C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\Max"
Min = "C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\Min"
Z-STD = "C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\Z-STD"
Z-Mean = "C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\Z-Mean"
Z-normalization = "C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\Z-normalization"

# Process: Project Raster
arcpy.ProjectRaster_management("", Projected_Raster, "", "NEAREST", "", "", "", "")

# Process: Clip
arcpy.Clip_management(Projected_Raster, "", ClipRaster, "", "", "NONE", "NO_MAINTAIN_EXTENT")

# Process: Resample
arcpy.Resample_management(ClipRaster, ResampleRaster, "", "NEAREST")

# Process: Cell Statistics (2)
arcpy.gp.CellStatistics_sa("C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\ResampleRaster", Mean, "MEAN", "DATA")

# Process: Cell Statistics (4)
arcpy.gp.CellStatistics_sa("C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\ResampleRaster", Min, "MINIMUM", "DATA")

# Process: Cell Statistics (3)
arcpy.gp.CellStatistics_sa("C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\ResampleRaster", Max, "MAXIMUM", "DATA")

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("(\"%ResampleRaster%\" - \"%Min%\") / (\"%Max%\"-\"%Min%\")", normalization)

# Process: Cell Statistics (6)
arcpy.gp.CellStatistics_sa("C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\normalization", Z-Mean, "MEAN", "DATA")

# Process: Cell Statistics (5)
arcpy.gp.CellStatistics_sa("C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\normalization", Z-STD, "STD", "DATA")

# Process: Raster Calculator (2)
arcpy.gp.RasterCalculator_sa("(\"%normalization%\"-\"%Z-Mean%\") / \"%Z-STD%\"", Z-normalization)

