# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# BuildComprehensiveFeatureSet.py
# Created on: 2024-02-02 20:13:52.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
Heat = "C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\Heat"
HeatData_TXT = "C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\HeatData.TXT"
Water = "C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\Water"
WaterData_TXT = "C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\WaterData.TXT.TXT"
Air = "C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\Air"
AirData_TXT_TXT = "C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\AirData.TXT.TXT"
ComprehensiveFeatureSet = "C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\ComprehensiveFeatureSet"

# Process: Principal Components
arcpy.gp.PrincipalComponents_sa("", Heat, "", HeatData_TXT)

# Process: Principal Components (2)
arcpy.gp.PrincipalComponents_sa("", Water, "", WaterData_TXT)

# Process: Principal Components (3)
arcpy.gp.PrincipalComponents_sa("", Air, "", AirData_TXT_TXT)

# Process: Composite Bands
arcpy.CompositeBands_management("C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\Heat;C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\Water;C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\Air", ComprehensiveFeatureSet)

