# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# MeasureClimateHeterogeneity.py
# Created on: 2024-02-02 20:12:29.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
SpatialUnit = "SpatialUnit"
FeatureClass = "SpatialUnit\\FeatureClass"
ComprehensiveFeatureSet = "C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\ComprehensiveFeatureSet"
ClimateHeterogeneityMeasurement = "C:\\Users\\fengyuning\\Documents\\ArcGIS\\Default.gdb\\ClimateHeterogeneityMeasurement"

# Process: Iterate Feature Classes
arcpy.IterateFeatureClasses_mb(SpatialUnit, "", "", "NOT_RECURSIVE")

# Process: Composite Bands
arcpy.CompositeBands_management("", ComprehensiveFeatureSet)

# Process: Zonal Statistics
arcpy.gp.ZonalStatistics_sa(FeatureClass, "", ComprehensiveFeatureSet, ClimateHeterogeneityMeasurement, "MEAN", "DATA")

